### ISSUE TITLE
Will this work with Keysticks?

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Kytech/xbox360wirelesschatpad#61]
```
Will this work with Keysticks? I do not use Xpadder. Thanks for your work. 

```

Original issue reported on code.google.com by `MTarpey1...@gmail.com` on 2 Feb 2015 at 7:00

**Comment by Kytech** [comment]
Closing due to no response as it is expected to work with keysticks. Will reopen/open new issue if incompatibility is found.
