### ISSUE TITLE
Key combo implementation and its importance.

### ISSUE THREAD

**Issue by waonboy** [Kytech/xbox360wirelesschatpad#76]
First of all, please forgive my poor English.
This is a great tool, but I would like you to implement a key combo.
I did a key mapping for ChatPad using visual studio but I wasn't an expert in C# so I couldn't implement the key combo.
It seems that there is no update for a while, but I am waiting for the next update.
Thank you very much.

**Comment by Kytech** [comment]
Duplicate of #66 

Custom keyboard combinations are currently on the backlog and have been requested in the linked issue. Haven't been able to do much with the program lately, so I can't really offer a time frame at this point.
