### ISSUE TITLE
Is that chatpad meant to be able to be used as a keyboard in Windows not just in the input box in .exe file?

### ISSUE THREAD

**Issue by cjwomack** [Kytech/xbox360wirelesschatpad#80]
I'm not sure whether I should be able to use this as a keyboard in Windows.

**Describe the bug**
I'm not sure whether I should be able to use this as a keyboard in Windows.

**Context of bug**
Can only type in input box in the application Xbox 360 Wireless Chatpad.exe

**To Reproduce**
Clear steps to reproduce the behavior:
1. Can only type in input box in Xbox 360 Wireless Chatpad.exe

**Expected behavior**
I assume I would be able to use as keyboard (But it doesn't say that explicitly re github??)

**Screenshots**
N/A

**Installation details**
 - Windows Version Windows 10 OS Build 19045.2728
 - Application Version [e.g. 22] Most recent
 - If install issue: libusb and vJoy versions N/A

**Additional context/details**
By the way, you need to update the version of vJoy that one can install. The game controller doesn't work in Windows 10 with vJoy 2.0.2

**Comment by Kytech** [comment]
You should be able to use the keyboard throughout Windows. I'd suggest trying to run the application as an administrator if you haven't already to see if that makes a difference. I don't know if Windows has started sandboxing or blocking keyboard input from unprivileged apps in more recent versions or under some certain configurations since I need to get this software setup for testing on one of my more recent machines, so I'd suggest you start with that and we can go from there.

**Comment by Kytech** [comment]
You should be able to use the chatpad in other applications, but it may not support any keyboard shortcuts in the OS itself. The API that this app is using only sends key events to the active window.

I'd suggest trying to run the application as an administrator if you haven't already to see if that makes a difference if you're finding other applications aren't receiving input when they are in focus. I don't know if beyond that, Windows has started sandboxing or blocking keyboard input from unprivileged apps in more recent versions or under some certain configurations, so it's worth trying that.

**Comment by cjwomack** [comment]
Hi there,

Looks like I only tested with a internet browser that has a problem with some keyboards, oops....

And it is working in other applications....

[AVG Secure Browser with problem with keyboards](https://support.avg.com/answers?id=9065p0000010wwMAAQ)

Thank you for getting back to me so fast though.
